My_Music_App/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('My_Music_App.common.urls')),
    path('album/', include('My_Music_App.album.urls')),
    path('profile/', include('My_Music_App.user_profile.urls')),
]

My_Music_App/user_profile/urls.py
from django.urls import path, include
from My_Music_App.user_profile import views

urlpatterns = [
    path('details/', views.user_profile_details, name='user-profile-details'),
    path('delete/', views.user_profile_delete, name='user-profile-delete'),
    path('edit/', views.user_profile_edit, name='user-profile-edit'),

]

My_Music_App/album/models.py
from django.db import models
from django.core.validators import MinValueValidator

from My_Music_App.user_profile.models import Profile


# Create your models here.


class Album(models.Model):
    album_name = models.CharField(max_length=30, unique=True, blank=False, null=False)
    artist = models.CharField(max_length=30, blank=False, null=False)
    some_choices = (
        ("Pop Music", "Pop Music"),
        ("Jazz Music", "Jazz Music"),
        ("R&B Music", "R&B Music"),
        ("Rock Music", "Rock Music"),
        ("Country Music", "Country Music"),
        ("Dance Music", "Dance Music"),
        ("Hip Hop Music", "Hip Hop Music"),
        ("Other", "Other")
    )
    genre = models.CharField(max_length=30, blank=False, null=False, choices=some_choices)
    description = models.TextField(blank=True, null=True)
    image_url = models.URLField(blank=False, null=False)
    price = models.FloatField(blank=False, null=False, validators=[MinValueValidator(0.0)])

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def names_of_songs_in_album(self):
        id = self.songs_set.values_list('id', flat=True)
        name = self.songs_set.values_list('name', flat=True)
        concatenated_list = []
        for i in range(len(id)):
            element = f'{id[i]}. {name[i]}'
            concatenated_list.append(element)
        return concatenated_list

    def songs_in_album(self):
        return self.songs_set.all()
    #
    # def __str__(self):
    #     return self.album_name

My_Music_App/user_profile/models.py
from django.core.validators import RegexValidator, MinLengthValidator
from django.core.validators import MinValueValidator
from django.db import models

# Create your models here.


class Profile(models.Model):
    username = models.CharField(max_length=15, blank=False, null=False,
                                validators=[MinLengthValidator(2),
                                            RegexValidator(
                                            regex=r'^[a-zA-Z0-9_]+$',
                                            message='Ensure this value contains only letters, numbers, and underscore.'
                                                            )
                                            ]
                                )
    email = models.EmailField(blank=False, null=False)
    age = models.PositiveIntegerField(blank=True, null=True)
    password = models.CharField(max_length=20)

My_Music_App/user_profile/forms.py
from django import forms
from My_Music_App.user_profile.models import Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'age': forms.NumberInput(attrs={'placeholder': 'Age'}),
            'password': forms.TextInput(attrs={'placeholder': 'Choose password'})
        }


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['password']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'age': forms.NumberInput(attrs={'placeholder': 'Age'}),
        }

My_Music_App/user_profile/views.py
from django.shortcuts import render, redirect

from My_Music_App.user_profile.forms import ProfileEditForm
from My_Music_App.user_profile.models import Profile


# Create your views here.


def user_profile_details(request):
    context = {
        "profile": Profile.objects.first()
    }
    return render(request, template_name='user_profile/profile-details.html', context=context)


def user_profile_delete(request):
    profiles = Profile.objects.all()
    if request.method == 'POST':
        profiles.delete()
        return redirect('homepage')
    return render(request, template_name='user_profile/profile-delete.html')


def user_profile_edit(request):
    profile = Profile.objects.first()
    form = ProfileEditForm(instance=profile)
    context = {
        'profile': profile,
        'form': form,
    }

    if request.method == 'POST':
        form = ProfileEditForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('user-profile-details')

    return render(request, template_name='user_profile/profile-edit.html', context=context)

templates/user_profile/profile-delete.html
{% extends 'base.html' %}

{% block content %}


<!-- Delete Profile Page-->
<section id="detailsPage">
    <div class="wrapper">
        <div class="profileText">

            <!-- Delete Profile Form -->
            <h1>Are you sure you want to delete your profile?</h1>
            <form method="post" {% url 'user-profile-delete' %}>
                <!-- Confirm Button -->
                {% csrf_token %}
                <button class="delete-profile" type="submit">Delete</button>
            </form>
            <!-- End Delete Profile Form -->

        </div>
    </div>
</section>


{% endblock %}

templates/user_profile/profile-details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!--Details Page-->
<section id="detailsPage">
    <div class="wrapper">
        <div class="profilePage">
            <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
                 alt="Profile Image">
        </div>

        <div class="profileText">
            <!-- Profile Info -->
            <h1>Username: {{ profile.username }}</h1>
            <h1>Email: {{ profile.email }}</h1>
            <h1>Age: {{ profile.age }}</h1>
            <h1>Albums: {{ profile.album_set.count }}</h1>
        </div>

        <div class="actionBtn">
            <!-- Button for Deleting the Profile -->
            <a href="{% url 'user-profile-delete' %}" class="remove">Delete</a>
        </div>

        <div class="actionBtn">
            <!-- Button for Editing the Profile -->
            <a href="{% url 'user-profile-edit' %}" class="edit">Edit</a>
        </div>

    </div>
</section>
{% endblock %}

templates/user_profile/profile-edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!--Details Page-->
<section id="detailsPage">
    <div class="wrapper_edit">
        <div class="profilePage">
            <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
                 alt="Profile Image">
        </div>

        <div class="profileText">
            <fieldset>
            <!-- Profile Info -->
            <form method="post">
                {% csrf_token %}
                <h1>Username: {{ form.username }}</h1>
                <h1>Email: {{ form.email }}</h1>
                <h1>Age: {{ form.age }}</h1>
                <button class="edit-profile" type="submit">Save changes</button>
            </form>
                </fieldset>

        </div>

    </div>
</section>
{% endblock %}